"""add_skills_tables_with_subscriptions_and_stats

Revision ID: 227f973e36f0
Revises: c8aa600e97c2
Create Date: 2026-01-20 23:55:51.948026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '227f973e36f0'
down_revision = 'c8aa600e97c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check which tables already exist
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # First, create skills table if it doesn't exist
    if 'skills' not in existing_tables:
        op.create_table('skills',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('display_name', sa.String(length=200), nullable=False),
        sa.Column('version', sa.String(length=20), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('applicable_roles', sa.JSON(), nullable=True),
        sa.Column('requirements', sa.JSON(), nullable=True),
        sa.Column('author', sa.String(length=100), nullable=True),
        sa.Column('source', sa.String(length=200), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_builtin', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_skill_name')
        )
        
        # Only create indexes if table was just created
        with op.batch_alter_table('skills', schema=None) as batch_op:
            batch_op.create_index('idx_skills_tenant_category', ['tenant_id', 'category'], unique=False)
            batch_op.create_index('idx_skills_tenant_created', ['tenant_id', 'created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
            batch_op.create_index(batch_op.f('ix_skills_is_active'), ['is_active'], unique=False)
            batch_op.create_index(batch_op.f('ix_skills_tenant_id'), ['tenant_id'], unique=False)
    
    # Then create dependent tables
    if 'skill_usage_stats' not in existing_tables:
        op.create_table('skill_usage_stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),
        sa.Column('usage_count', sa.Integer(), nullable=False),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=False),
        sa.Column('failure_count', sa.Integer(), nullable=False),
        sa.Column('avg_execution_time', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'skill_id', name='uq_tenant_skill_stat')
        )
        with op.batch_alter_table('skill_usage_stats', schema=None) as batch_op:
            batch_op.create_index('idx_skill_usage', ['skill_id', 'usage_count'], unique=False)
            batch_op.create_index('idx_tenant_skill', ['tenant_id', 'skill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_skill_usage_stats_skill_id'), ['skill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_skill_usage_stats_tenant_id'), ['tenant_id'], unique=False)

    if 'tenant_skill_subscriptions' not in existing_tables:
        op.create_table('tenant_skill_subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.Integer(), nullable=False),
        sa.Column('skill_id', sa.Integer(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('custom_config', sa.JSON(), nullable=True),
        sa.Column('subscribed_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'skill_id', name='uq_tenant_skill')
        )
        with op.batch_alter_table('tenant_skill_subscriptions', schema=None) as batch_op:
            batch_op.create_index('idx_tenant_enabled', ['tenant_id', 'enabled'], unique=False)
            batch_op.create_index(batch_op.f('ix_tenant_skill_subscriptions_skill_id'), ['skill_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_tenant_skill_subscriptions_tenant_id'), ['tenant_id'], unique=False)

    # No need to add indexes to discussion_sessions - they already exist from previous migration

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop dependent tables first
    with op.batch_alter_table('tenant_skill_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_skill_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_skill_subscriptions_skill_id'))
        batch_op.drop_index('idx_tenant_enabled')

    op.drop_table('tenant_skill_subscriptions')
    
    with op.batch_alter_table('skill_usage_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_usage_stats_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_skill_usage_stats_skill_id'))
        batch_op.drop_index('idx_tenant_skill')
        batch_op.drop_index('idx_skill_usage')

    op.drop_table('skill_usage_stats')
    
    # Drop skills table last
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_skills_is_active'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))
        batch_op.drop_index('idx_skills_tenant_created')
        batch_op.drop_index('idx_skills_tenant_category')
    
    op.drop_table('skills')
    
    # No need to remove indexes from discussion_sessions - not added in this migration

    # ### end Alembic commands ###
