"""Add multi-tenant support: Tenant model and tenant_id foreign keys

Revision ID: c8aa600e97c2
Revises: da0193d67076
Create Date: 2026-01-20 23:17:18.830803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8aa600e97c2'
down_revision = 'da0193d67076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建tenants表（使用SQLite IF NOT EXISTS判断）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    
    if 'tenants' not in inspector.get_table_names():
        op.create_table('tenants',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=200), nullable=False),
            sa.Column('quota_config', sa.JSON(), nullable=True),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('tenants', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tenants_created_at'), ['created_at'], unique=False)
    
    # 修改discussion_sessions表，添加tenant_id
    with op.batch_alter_table('discussion_sessions', schema=None) as batch_op:
        # 检查列是否已存在
        existing_columns = [c['name'] for c in inspector.get_columns('discussion_sessions')]
        if 'tenant_id' not in existing_columns:
            batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        
        # 检查索引是否存在
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('discussion_sessions')]
        if 'idx_tenant_created' not in existing_indexes:
            batch_op.create_index('idx_tenant_created', ['tenant_id', 'created_at'], unique=False)
        if 'idx_tenant_status' not in existing_indexes:
            batch_op.create_index('idx_tenant_status', ['tenant_id', 'status'], unique=False)
        if 'ix_discussion_sessions_tenant_id' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_discussion_sessions_tenant_id'), ['tenant_id'], unique=False)
        
        # 外键约束
        batch_op.create_foreign_key('fk_discussion_sessions_tenant', 'tenants', ['tenant_id'], ['id'])

    # 修改users表，添加tenant_id
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 检查列是否已存在
        existing_columns = [c['name'] for c in inspector.get_columns('users')]
        if 'tenant_id' not in existing_columns:
            batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        
        # 检查索引是否存在
        existing_indexes = [idx['name'] for idx in inspector.get_indexes('users')]
        if 'ix_users_tenant_id' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        
        # 外键约束
        batch_op.create_foreign_key('fk_users_tenant', 'tenants', ['tenant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 移除users表的tenant_id
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    # 移除discussion_sessions表的tenant_id
    with op.batch_alter_table('discussion_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_discussion_sessions_tenant', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_discussion_sessions_tenant_id'))
        batch_op.drop_index('idx_tenant_status')
        batch_op.drop_index('idx_tenant_created')
        batch_op.drop_column('tenant_id')
    
    # 删除tenants表
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_created_at'))
    op.drop_table('tenants')

    # ### end Alembic commands ###
