"""Add interventions field to DiscussionSession

Revision ID: da0193d67076
Revises: 002
Create Date: 2026-01-19 19:19:22.723059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0193d67076'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interventions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discussion_sessions', schema=None) as batch_op:
        batch_op.drop_column('interventions')

    # ### end Alembic commands ###
